title: 아이스크림 AIDT
description: AI 디지털 교과서 소개 사이트
author: 아이스크림미디어
url: "https://kimdeoksoon.github.io/AIDT"

# GitHub Pages 설정
baseurl: "/AIDT"
url: "https://kimdeoksoon.github.io"

# 빌드 설정
markdown: kramdown
highlighter: rouge

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 제외할 파일들
exclude:
  - README.md
  - .gitignore
  - _config.yml 